phrase:
  push:
    sources:
    - file: ./rockwallet/rockwallet/src/Strings/en.lproj/Localizable.strings
      project_id: "389f9cee76464e67a65ffd66d3f4d395"
      params:
        file_format: strings
        locale_id: en-US
        update_translations: true
    - file: ./rockwallet/rockwallet/Resources/InfoPlistLocalization/en.lproj/InfoPlist.strings
      project_id: "389f9cee76464e67a65ffd66d3f4d395"
      params:
        file_format: strings
        locale_id: en-US
        update_translations: true
    - file: ./rockwallet/rockwalletWidget/en.lproj/BreadWalletWidget.strings
      project_id: "fd548746242c61f1dbc394156c78b468"
      params:
        file_format: strings
        locale_id: en-US
        update_translations: true
  pull:
    targets:
    - file: ./rockwallet/rockwallet/src/Strings/<locale_code>.lproj/Localizable.strings
      project_id: "389f9cee76464e67a65ffd66d3f4d395"
      params:
        file_format: strings
        include_unverified_translations: true
        fallback_locale_id: en-US
        include_empty_translations: true
        encoding: UTF-8
    - file: ./rockwallet/rockwallet/Resources/InfoPlistLocalization/<locale_code>.lproj/InfoPlist.strings
      project_id: "389f9cee76464e67a65ffd66d3f4d395"
      params:
        file_format: strings
        include_unverified_translations: true
        fallback_locale_id: en-US
        include_empty_translations: true
        encoding: UTF-8
    - file: ./rockwallet/rockwalletWidget/<locale_code>.lproj/BreadwalletWidget.strings
      project_id: "fd548746242c61f1dbc394156c78b468"
      params:
        file_format: strings
        include_unverified_translations: true
        fallback_locale_id: en-US
        include_empty_translations: true
        encoding: UTF-8
